### ISSUE TITLE
URLFormatter strips custom urls' paths

### ISSUE THREAD

**Issue by simad** [gocardless/gocardless-pro-java#10]
Hey there :)
We have just started using your sdk to integrate with GoCardless. As part of our development process we create stubs of all of our external dependencies, and we use those for a layer of testing. 

We are creating a client and supplying an internal url, using `GoCardlessClient.create(accessToken, clientUrl)`, where `clientUrl` is something like: `https://www.some.localdomain/a/b/`. 

Let's say that we hit the `/customers` endpoint; the client will try to call our stubs at:
`https://www.some.localdomain/customers` instead of the expected `https://www.some.localdomain/a/b/customers`.

I've traced the issue to this line:
https://github.com/gocardless/gocardless-pro-java/blob/master/src/main/java/com/gocardless/http/UrlFormatter.java#L20

`baseUrl.resolve(path)` returns the correct value if path does not have a leading `/` (e.g. `customers` instead of `/customers`).

I don't know if this is an expected behaviour, in that case we will have to deal with it (cue sunglasses) - but we would appreciate if you could allow multiple level of paths.

Thanks!

**Comment by timrogers** [comment]
@simad Thanks for reporting this issue!

What's going on makes sense, as the [`resolve` method in okhttp's HttpUrl](https://square.github.io/okhttp/2.x/okhttp/index.html?com/squareup/okhttp/HttpUrl.html) is designed to behave a bit like a web browser. Let's say you're on <https://gocardless.com/path/to/pricing>. `<a href="/customers">` would take me to <https://gocardless.com/customers>  whereas `<a href="customers">` would take me to <https://gocardless.com/path/to/customers>. This is doing the same thing, from the starting point of your `baseUrl`.

We'll have a think about fixing this by removing the leading slashes from our paths, which are returned from the `getPathTemplate` method on our requests.

But for now, I'd suggest just working around this, unless it's really not viable.

@matt-thomson I'd be interested to hear your thoughts on this one.

**Comment by timrogers** [comment]
@simad We've implemented a fix to this, which we should have released in the next couple of days. We're going to stripe the slashes from our paths as I [suggested](https://github.com/gocardless/gocardless-pro-java/issues/10#issuecomment-366955721) above. Do let us know if we can help with anything else.

**Comment by jacobpgn** [comment]
Thanks @simad – [v2.9.0](https://github.com/gocardless/gocardless-pro-java/releases/tag/v2.9.0) should deal with this!

<img width="149" alt="screen shot 2018-02-21 at 14 42 57" src="https://user-images.githubusercontent.com/6728978/36486076-8bb0f4f4-1715-11e8-82b4-635ffe4c7018.png">
