### ISSUE TITLE
java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by DanailMinchev** [gocardless/gocardless-pro-java#12]
Hi there! :)

We use your Java SDK in our application and we have noticed that if application runs for a while, making many calls to GoCardless via your SDK, we eventually start to receive `java.net.SocketTimeoutException: connect timed out` errors when calling any method in the SDK that communicates with GoCardless.

We’ve reproduced and debugged the problem and traced it to [rawClient.newCall(request).execute()](https://github.com/gocardless/gocardless-pro-java/blob/v3.5.0/src/main/java/com/gocardless/http/HttpClient.java#L140): 
the `com.squareup.okhttp.Call#execute` call throws the `java.net.SocketTimeoutException`, which is handled at https://github.com/gocardless/gocardless-pro-java/blob/v3.5.0/src/main/java/com/gocardless/http/HttpClient.java#L142.

We think that the ultimate cause is that your SDK is not closing the connections properly, as required by the OkHttp library.

From the Javadoc of [com.squareup.okhttp.Call#execute](https://github.com/square/okhttp/blob/parent-2.7.5/okhttp/src/main/java/com/squareup/okhttp/Call.java#L57) method, which is part of `okhttp-2.7.5.jar`:

```
The caller may read the response body with the response's
{@link Response#body} method.  To facilitate connection recycling, callers
should always {@link ResponseBody#close() close the response body}.
```

Examining the code shows that you receive the `response` inside [HttpClient.execute](https://github.com/gocardless/gocardless-pro-java/blob/v3.5.0/src/main/java/com/gocardless/http/HttpClient.java#L140)
and it is eventually passed to [HttpClient.parseResponseBody](https://github.com/gocardless/gocardless-pro-java/blob/v3.5.0/src/main/java/com/gocardless/http/HttpClient.java#L150). Here, you
get the body as a `charStream` and parse it, but I cannot see that it is closed anywhere.

As stated in Javadoc, callers should always close the response body using [ResponseBody#close()]( https://github.com/square/okhttp/blob/parent-2.7.5/okhttp/src/main/java/com/squareup/okhttp/ResponseBody.java#L91).

While investigating this, we found an OkHttp issue: https://github.com/square/okhttp/issues/3146.

While I’m not exactly sure how OkHttp works, it probably uses a connection pool, which could become filled with dead socket connections because they are not being closed.

In the next major version of OkHttp (version 3.x), which is not used in the current SDK, you can use [ConnectionPool.evictAll](http://square.github.io/okhttp/3.x/okhttp/okhttp3/ConnectionPool.html#evictAll--) as described in https://github.com/square/okhttp/issues/3146#issuecomment-287194996.

If you do upgrade OkHttp, it might be useful if your SDK could expose the `HttpClient` object to consumers so that we can configure it to meet our needs.

**Comment by matt-thomson** [comment]
Hi @DanailMinchev, thanks for the detailed investigation!

Please could you confirm which version of the library you're using? We recently released v3.5.1, which reads response bodies differently, and I think it addresses this issue (see [here](https://github.com/gocardless/gocardless-pro-java/commit/3c6a6d3fa03186c2c24ecda80c25c758e9e2c375#diff-de1294ad9910be31b348b006e9646db1R160)).  If you're on an earlier version, please could you upgrade and let us know how it goes?

**Comment by DanailMinchev** [comment]
Hi @matt-thomson ,

Thank you for your quick reply!

We just upgraded GoCardless SDK from `3.4.0` to `3.5.1`.
I am not sure if the issue will be fixed in the latest `3.5.1` release because as I can see old OkHttp [string()](https://github.com/square/okhttp/blob/parent-2.7.5/okhttp/src/main/java/com/squareup/okhttp/ResponseBody.java#L82) method is not closing the `ResponseBody` automatically or is it done somewhere else?
In the latest version it is closing the body according to Javadoc -  https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/ResponseBody.java#L165 and https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/ResponseBody.java#L177

**Comment by matt-thomson** [comment]
`string` calls through to `bytes`, which does close the underlying source.  See https://github.com/square/okhttp/blob/parent-2.7.5/okhttp/src/main/java/com/squareup/okhttp/ResponseBody.java#L56-L60.

Thanks for upgrading - let us know if this helps!

**Comment by DanailMinchev** [comment]
@matt-thomson Thank you for your clarification!

We will let you know if we encounter this issue again, this should help! :)

**Comment by DanailMinchev** [comment]
@matt-thomson Are you sure this bug has definitely been squashed?

We are using the latest `3.7.0` version but we are still seeing `connect timed out` errors after the application has been making calls using the library for a while.

**Comment by cristiangreco** [comment]
Hey @DanailMinchev thanks for reporting this problem!

To help us understand better the nature of the problem would be great if you could provide:
- a full stacktrace that shows where `SocketTimeoutException` generates from, specifically which parts of okhttp is throwing the exception
- any code snippet that would help us reproduce and isolate the problem (as far as I understand you're hitting it frequently and are able to consistently reproduce it)

Thanks!

**Comment by DanailMinchev** [comment]
Hi @cristiangreco ,

Thanks for the reply!

- The problem is hard to reproduce, because it takes a lot of time when it happens. Basically we have smoke tests running every X minutes and we hit the issue after few weeks (which means we need to do a lot of payments). In my first post https://github.com/gocardless/gocardless-pro-java/issues/12#issue-332799862 I explained exactly where it's thrown, mainly in https://github.com/gocardless/gocardless-pro-java/blob/v3.5.0/src/main/java/com/gocardless/http/HttpClient.java#L142

- We use the SDK in https://github.com/alphagov/pay-direct-debit-connector/ and we create a customer, bank account, mandate, also we check for bank details there as SDK calls. Not sure if I can provide you with another application, but I can explain the sequences of SDK methods which we call

Thanks!

**Comment by cristiangreco** [comment]
Hi @DanailMinchev!

Would you be able to provide a stacktrace from your smoke tests? I'm interested in seeing which code in okhttp is raising that exception, to possibly validate the hypothesis that it is caused by connection recycling.

**Comment by DanailMinchev** [comment]
Hi @cristiangreco ,

Yes, sure, I will try to reproduce it and I will get back to you (probably it may take more than 2-3 weeks as explained above).

Thanks

**Comment by DanailMinchev** [comment]
Hi again @cristiangreco ,

We were able to reproduce the issue:

Here is the stacktrace:
```
com.gocardless.http.GoCardlessNetworkException: Failed to execute request
com.gocardless.http.HttpClient.execute(HttpClient.java:141)
com.gocardless.http.HttpClient.execute(HttpClient.java:80)
com.gocardless.http.PostRequest.execute(PostRequest.java:21)
uk.gov.pay.directdebit.common.clients.GoCardlessClientWrapper.validate(GoCardlessClientWrapper.java:74)
uk.gov.pay.directdebit.common.clients.GoCardlessClientFacade.validate(GoCardlessClientFacade.java:76)
uk.gov.pay.directdebit.mandate.services.gocardless.GoCardlessService.validate(GoCardlessService.java:112)
uk.gov.pay.directdebit.payers.resources.PayerResource.validateBankAccount(PayerResource.java:101)
sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
org.glassfish.jersey.internal.Errors.process(Errors.java:315)
org.glassfish.jersey.internal.Errors.process(Errors.java:297)
org.glassfish.jersey.internal.Errors.process(Errors.java:267)
org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
uk.gov.pay.directdebit.app.filters.LoggingFilter.doFilter(LoggingFilter.java:45)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
org.glassfish.jersey.internal.Errors.process(Errors.java:315)
org.glassfish.jersey.internal.Errors.process(Errors.java:297)
org.glassfish.jersey.internal.Errors.process(Errors.java:267)
org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
uk.gov.pay.directdebit.app.filters.LoggingFilter.doFilter(LoggingFilter.java:45)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:674)
io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
org.eclipse.jetty.server.Server.handle(Server.java:531)
org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
java.lang.Thread.run(Thread.java:748)
by: java.net.SocketTimeoutException: connect timed out
java.net.PlainSocketImpl.socketConnect(Native Method)
java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
java.net.Socket.connect(Socket.java:589)
com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:120)
com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
com.squareup.okhttp.Call.getResponse(Call.java:286)
com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
com.gocardless.http.LoggingInterceptor.intercept(LoggingInterceptor.java:21)
com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
com.squareup.okhttp.Call.execute(Call.java:80)
com.gocardless.http.HttpClient.execute(HttpClient.java:139)
 70 more
com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:674)
io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
org.eclipse.jetty.server.Server.handle(Server.java:531)
org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
java.lang.Thread.run(Thread.java:748)
by: java.net.SocketTimeoutException: connect timed out
java.net.PlainSocketImpl.socketConnect(Native Method)
java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
java.net.Socket.connect(Socket.java:589)
com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:120)
com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
com.squareup.okhttp.Call.getResponse(Call.java:286)
com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
com.gocardless.http.LoggingInterceptor.intercept(LoggingInterceptor.java:21)
com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
com.squareup.okhttp.Call.execute(Call.java:80)
com.gocardless.http.HttpClient.execute(HttpClient.java:139)
... 70 common frames omitted
```

**Comment by DanailMinchev** [comment]
Hi @cristiangreco ,

We were able to identify the issue.

The `networkaddress.cache.ttl` setting was changed with:
```
java.security.Security.setProperty("networkaddress.cache.ttl", "1");
```
but it was not the problem.

The problem is that when we set the proxy and build the GoCardless SDK instance and keep it in memory (we have pool of GoCardless SDK instances because it will connect to various accounts/merchants) then if our cloud provider changes the IP of the load balancer of the egress proxy we will do our requests to an old/invalid IP of the proxy and then they will fail.
To reproduce that as well you can initialise SDK instance with some proxy domain (not IP address), for example `proxy.internal.example.com` described below, then try to change the domain to resolve to other IP, the existing in-memory instance will not try to resolve the domain again hence it will query an old IP.

More details on the issue:

Initially we were using [withProxy](https://github.com/gocardless/gocardless-pro-java/blob/88abba3f9a1e0a6f36a4d5bb1371bbfec834a467/src/main/java/com/gocardless/GoCardlessClient.java#L80) method to configure proxy as described in your [README.md -> Initializing the client](https://github.com/gocardless/gocardless-pro-java/blob/88abba3f9a1e0a6f36a4d5bb1371bbfec834a467/README.md#initializing-the-client) and we configure it like [this](https://github.com/alphagov/pay-direct-debit-connector/blob/82476e3a26546d825bc05f065d6497a019b4770a/src/main/java/uk/gov/pay/directdebit/common/clients/GoCardlessClientFactory.java#L49).

After debugging the live instance we found out that we are using invalid IP (probably because it was renewed with new one after few weeks by our cloud provider)
<img width="899" alt="okhttp - wrong proxy ip" src="https://user-images.githubusercontent.com/7883702/48779233-0de07780-eccf-11e8-86d7-808da850fddd.png">
So, the SDK was initialised with something like:
```
Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("proxy.internal.example.com", 8080));

GoCardlessClient client = GoCardlessClient.newBuilder(accessToken)
    .withEnvironment(GoCardlessClient.Environment.SANDBOX)
    .withProxy(proxy)
    .build();
```
and the `proxy` was instantiated with something like `proxy.internal.example.com/172.16.254.1`, at some point `172.16.254.1` was not valid anymore but the instance was not re-resolving `proxy.internal.example.com` into the new IP address.

So, we needed to initialise the proxy for each request to be able to retrieve the valid proxy IP (because we keep the SDK instances in memory and do not destroy them).
We have created custom [ProxySelector](https://github.com/alphagov/pay-direct-debit-connector/pull/271)

It will be nice if you could expose `withProxySelector` in the SDK (as you did for [withProxy](https://github.com/gocardless/gocardless-pro-java/blob/88abba3f9a1e0a6f36a4d5bb1371bbfec834a467/src/main/java/com/gocardless/GoCardlessClient.java#L80)), this way we can configure the specific proxy selector only for GoCardlessSDK

Thanks

**Comment by DanailMinchev** [comment]
I guess this issue can be closed now as the problem was identified, thank you

**Comment by cristiangreco** [comment]
@DanailMinchev glad to hear this has been resolved, and thanks for the detailed explanation!

Would you mind opening a "feature request" ticket to discuss and evaluate your suggestion in more detail?

**Comment by DanailMinchev** [comment]
Thanks @cristiangreco , I've created a new GitHub issue (feature request).

Also, I am not sure if there is a way to initialise the `java.net.Proxy` which is using `java.net.InetSocketAddress` and set the proxy to use domain names (the original value `proxy.internal.example.com`) instead of resolved IP addresses as in the code example below:

```
Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("proxy.internal.example.com", 8080));

GoCardlessClient client = GoCardlessClient.newBuilder(accessToken)
    .withEnvironment(GoCardlessClient.Environment.SANDBOX)
    .withProxy(proxy)
    .build();
```
