### ISSUE TITLE
Any plan to upgrade to okhttp3?

### ISSUE THREAD

**Issue by heathd** [gocardless/gocardless-pro-java#13]
The version of okhttp used by this client library is [2.7.5](https://github.com/gocardless/gocardless-pro-java/blob/master/build.gradle#L26). This version is [more than 2 years old](https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-275).

Whilst we are not aware of any specific issues with 2.7.5 at present, it seems likely that ongoing improvements and bugfixes to the okhttp library will be made on the okhttp3 branch.

Do you have any plans to upgrade?

**Comment by softmade-timobruentjen** [comment]
Well, this issue is now 3 years old, any plans on upgrading okhttp3? 2.7.5 is now more than 5 years away

**Comment by vdandugc** [comment]
closing this, v5.0.0 okhttp v4.9
