### ISSUE TITLE
Interface abstractions

### ISSUE THREAD

**Issue by craigjbass** [gocardless/gocardless-pro-java#2]
When I define my code, I want to depend on abstract boundary interfaces not concrete implementations.

e.g.

Scala
```scala
class SomeUseCase( gocardless:SomeGoCardlessUseCase ) {
   def execute(): Unit = {
       gocardless doSomething
   }
}
```

Testing using JUnit
```java
public class SomeUseCaseTest {
    @Test
    public void testSomething() {
        new SomeUseCase( new SomeGoCardlessUseCase() {
          ... create a test double stub ...
        } );
    }

}
```

Currently I can do this by defining facades, but this is tedious.

**Comment by craigjbass** [comment]
Hey guys, any update on this. I would really like to improve your Java templates that you use to generate this code, but this part isn't open source.

**Comment by matt-thomson** [comment]
Hi Craig,

Thanks for your feedback on the Java library.  In designing this library, we prioritised making the interface discoverable via a simple fluent builder pattern, over using abstract interfaces for mocking.  As a result, we would discourage mocking the library's interface directly, as it would be awkward to do so.

As you suggest, we would recommend creating a facade that wraps the GoCardless library for your specific use case.  This will allow you to mock an interface that you own elsewhere in your unit tests, and to check your integration with GoCardless in an integration test.

Regarding open-sourcing the templates: we're hoping to be able to do this soon (hopefully in the next couple of weeks).

**Comment by craigjbass** [comment]
@matt-thomson I think it's possible to design the API to provide something that is capable of both.

In Ruby fluent interfaces are fine because you have infinite interface segregation. In Java is creates painful scenarios :-1:
