### ISSUE TITLE
java.lang.IllegalStateException: Not a JSON Object: null

### ISSUE THREAD

**Issue by mantono** [gocardless/gocardless-pro-java#29]
>Caused by: java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
	at com.gocardless.http.ResponseParser.parseSingle(ResponseParser.java:28)
	at com.gocardless.http.ResponseParser.parseError(ResponseParser.java:55)
	at com.gocardless.http.HttpClient.handleErrorResponse(HttpClient.java:161)
	at com.gocardless.http.HttpClient.execute(HttpClient.java:144)
	at com.gocardless.http.HttpClient.executeWrapped(HttpClient.java:86)
	at com.gocardless.http.PostRequest.executeWrapped(PostRequest.java:33)

After updating from version 3.7.1 to version 3.7.3 we get the exception above. How ever, reverting back to 3.7.1 does not help so this was probably a coincidence. We are currently unable to create any new subscriptions for our customers.

**Comment by Greyschale** [comment]
@mantono could you please provide some more information, such as an example snippet of the code you're trying to run? It seems like if it happens in the older version as well, it's not something that's changed between 3.7.1 and 3.7.3 but there might be something else going on.

**Comment by mantono** [comment]
I will provide you with some better example tomorrow. We did a rollback of our production code and the problem dissappeared, so it seems that something in our input changed that causes this problem. In other words, I am quite confident that we might be able to pinpoint the cause of this exception.

**Comment by mantono** [comment]
We have been able to recreate the issue in development environment and find the cause. The idempotence key that we were using when sending the request is (or was supposed to be) a SHA-1 hash that is converted from a byte array to a string with hexadecimal encoding. Unfortunately, the encoding was done incorrectly which resulted in non-ASCII characters. This explains why we at some point also got the exception _InvalidApiUsageException_ with the error message
>One of your headers contained a non US-ASCII character, or was not encoded properly. Only US-ASCII characters should be used in headers.

which we initially thought was an unrelated issue. I still don't know what response your server is trying to send or why it fails, but maybe it tries to include the broken idempotence key in the respone and brakes the response as well?

I can give you some more exact example input if that is of any help. The endpoint where we encountered this problem was `createCustomer`, but I guess this problem is not unique for that request.

**Comment by paprikati** [comment]
I believe we've made some changes in this area. Could you confirm whether you still get the java.lang.IllegalStateException?

**Comment by mantono** [comment]
Hi @paprikati! I am sorry, but I just quit the company two days ago where I integrated towards GoCardless. But maybe I will be able to look into this on my free time, it shouldn't be very hard to replicate the issue with an older version and see if it still persists in more recent versions. I'll see if I can find some time to look into this over the next couple of days.

**Comment by smur89** [comment]
Similar/Same issue here: https://github.com/gocardless/gocardless-pro-java/issues/49

**Comment by mantono** [comment]
I wouldn't say that is the same issue. This has quite different causes. I have how ever encountered that issue as well @smur89 and I've considered reporting it, but it seems you were quicker than me.

**Comment by vdandugc** [comment]
This is fixed by latest release [4.8.0](https://github.com/gocardless/gocardless-pro-java/releases/tag/v4.8.0)
