### ISSUE TITLE
Idempotency Keys

### ISSUE THREAD

**Issue by tom-smalls** [gocardless/gocardless-pro-java#4]
I am currently integrating with go-cardless via the Java library you've provided, however I've come into an issue in regards to idempotent behaviour. Your API documentation talks about setting a HTTP header "Idempotency-Key" to ensure that creation requests have idempotent behaviour; this feature does not seem to be available via the Java library. I couldn't see header being added in your HttpClient, nor are there any methods on your request builders that allow for this header to be added.

Is my assertion correct, and if so, is there intention of introducing this header to the library?

Thanks,

Tom

**Comment by matt-thomson** [comment]
Hi Tom - you're right that we don't currently handle idempotent creates in the Java library.  This is on our roadmap, but we don't have the work scheduled as yet.  If there are any updates I'll let you know here.

**Comment by tom-smalls** [comment]
It feels strange to have a idempotent key for creation actions to be honest via POST. HTTP PUT should be idempotent so why not just make creation actions PUT methods, and then embed this functionality into the calls?

**Comment by matt-thomson** [comment]
Sorry for the delay on this one - as mentioned in #5, we've rolled out a new client that includes this behaviour.
