### ISSUE TITLE
Unrecognized field "bank_account_id"

### ISSUE THREAD

**Issue by asalikiryaki** [gocardless/gocardless-pro-java#43]
Hello, we are using version 3.14 of this library and we are getting the following exception:

> com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "bank_account_id" (class com.gocardless.resources.Event$Details), not marked as ignorable (6 known properties: "scheme", "origin", "reason_code", "cause", "description", "will_attempt_retry"])

It looks like this field was not introduced in version 3.15 either.
Seem like this field was introduced in the response on March 26, since this is the date when we started getting exceptions on our end.

**Comment by paprikati** [comment]
Hi,
This is due to a new event type which we introduced. I will look at this this afternoon.

Thanks

**Comment by paprikati** [comment]
This should be fixed in v3.15.1

**Comment by TamasGorgics** [comment]
Seems to be working!
