### ISSUE TITLE
Missing release 4.7.0 on Maven Central and skipped 4.6.0 tag on GitHub repositories

### ISSUE THREAD

**Issue by DanielMedinaStacey** [gocardless/gocardless-pro-java#64]
Hi, I have noticed two minor issues (maybe I'm being nitpicky) about versioning and consistency between the GitHub repository and the Maven Central repository which could be related:

1. [Release 4.7.0](https://github.com/gocardless/gocardless-pro-java/releases/tag/v4.7.0) is still not available on [Maven Central]( https://repo1.maven.org/maven2/com/gocardless/gocardless-pro/) as of 2021-01-23, 12 days after being released.
2. The[ latest version available on Maven, 4.6.0](https://repo1.maven.org/maven2/com/gocardless/gocardless-pro/4.6.0/), is not tagged as a release on GitHub, which skips directly from 4.5.0 to 4.7.0. After some investigation, I have found that version 4.6.0 on Maven corresponds to commit [345ccc346d2e5624ec45902e9efb194b966a2fa2](https://github.com/gocardless/gocardless-pro-java/commit/345ccc346d2e5624ec45902e9efb194b966a2fa2).

I know these are very minor details, but I just happened to notice them after wondering why version 4.7.0, which is suggested in the current README.md, was not available on Maven.

**Comment by danwakefield** [comment]
We are aware the 4.7 is not available. We are in the process of automating our Java releases and it will become available when this is complete.

**Comment by vdandugc** [comment]
A new version [4.8.0](https://repo.maven.apache.org/maven2/com/gocardless/gocardless-pro/4.8.0/) is now published to maven.
