### ISSUE TITLE
Organization webhook events return null in the ID field

### ISSUE THREAD

**Issue by jakubskrzypek** [gocardless/gocardless-pro-java#74]
After clicking "Revoke access" by the partner in "Connected apps" from the GoCardless dashboard. After this action, we get an event that has a null value in the ID field.

```json
{
	"events": [
		{
			"id": null,
			"created_at": "2021-07-02T11:04:23.357Z",
			"resource_type": "organisations",
			"action": "disconnected",
			"links": {
				"organisation": "OR0000.."
			},
			"details": {
				"origin": "gocardless",
				"cause": "app_disconnected",
				"description": "Your app has been has disconnected from this organisation"
			},
			"metadata": {}
		}
	],
	"meta": {
		"webhook_id": "WB000..."
	}
}
`````

**Comment by vdandugc** [comment]
hi, thanks for raising, this seems to be expected behaviour as mentioned [here](https://developer.gocardless.com/getting-started/partners/connecting-your-users-accounts/#handling-disconnections)
