### ISSUE TITLE
Event origin

### ISSUE THREAD

**Issue by mkbrv** [gocardless/gocardless-pro-java#8]
Currently in sandbox I receive the following event origin:
details":{"origin":"gocardless"} 

Is it possible that the origin could be environment related? I am asking because in our case in the same environment we will connect both to prod (real users) and sandbox (fake/test users). So it would be helpful to know where the event arrived from.

Also it would be helpful if in the sdk there would be a payload parser that would return a List of Events from the PayLoad.

**Comment by timrogers** [comment]
Hi @mkbrv - thanks for your feedback!

Could you think about having two separate endpoints for receiving live and sandbox webhooks respectively? We could definitely think about including this information in the payload (I'll make a note of that) but being able to receive both environments' webhooks in one place isn't really a case we're planning for at the moment.

At the moment, none of our libraries/SDKs have extra magic in them for dealing with webhooks. However, we would like to make this better. Until then, have you seen our Java code examples at <https://developer.gocardless.com/getting-started/api/staying-up-to-date-with-webhooks/?language=java>? I think they'll help.

**Comment by timrogers** [comment]
We've just made a change to add the `Origin` request header to our webhooks - you can use this to identify which GoCardless environment a webhook came from. It'll be <https://api.gocardless.com> in live, and <https://api-sandbox.gocardless.com> in sandbox.

**Comment by mkbrv** [comment]
Hi @timrogers,

Thank you for your quick reply. Neither of the above described issues were blocking me of course, I should have mentioned that. They were more like improvement suggestions.

Thank you for your quick reply :+1:

**Comment by timrogers** [comment]
No problem ❤️ We've made a note around improving webhook handling in our libraries, so I'll close this issue.
